### PR TITLE
Testing Bot AI

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves https://github.com/Keyrxng/UbiquityBotTesting/issues/33  

This pull request introduces several changes to the repository, primarily focusing on the addition of configuration files and submodules. Below is a summary of the changes made:

.gitignore:

A new .gitignore file has been added to the repository. It includes rules for ignoring various files and directories, such as /node_modules, /coverage, .next/, /build, .DS_Store, .pem, .env, .vercel, TypeScript build info files, and more.
.gitmodules:

A new .gitmodules file has been added, which defines submodules and their URLs. This includes submodules for forge-std, openzeppelinUpgradeable, and openzeppelin.
dapp/.gitmodules:

The .gitmodules file in the dapp/ directory has been updated to include submodules for openzeppelinUpgradeable and openzeppelin.
dapp/contracts/lib/openzeppelin:

A new subproject, openzeppelin, has been added under dapp/contracts/lib/. It references commit 8186c07a83c09046c6fbaa90a035ee47e4d7d785.
dapp/contracts/lib/openzeppelinUpgradeable:

Another subproject, openzeppelinUpgradeable, has been added under dapp/contracts/lib/. It references commit f4b309ae37dc650efa7523dd1230d230e3f452d7.
dapp/contracts/script/Counter.s.sol:

The file Counter.s.sol has been removed from the repository.
dapp/contracts/script/CounterDeploy.s.sol:

A new script file, CounterDeploy.s.sol, has been added. This script is used for deploying and initializing the Counter contract and related contracts.
dapp/contracts/src/Counter.sol:

The Counter contract has been updated to be UUPSUpgradeable. It includes initialization logic and functions for setting and incrementing a number. Additionally, it now has a getGap function to retrieve gap size.
dapp/contracts/src/CounterOneChange.sol:

A new contract, CounterOneChange, has been added. It is also UUPSUpgradeable and includes functions for setting, incrementing, decrementing a number, and getting gap size.
dapp/contracts/src/uupsProxy.sol:

A new contract, UupsProxy, has been added. It is used for proxying contract calls.
dapp/contracts/test/Counter.t.sol:

The test file for the Counter contract has been updated to work with the new contract implementation and includes tests for incrementing, setting, and upgrading.
dapp/foundry.toml:

The solc version in the foundry.toml configuration file has been updated to 0.8.20, and remappings for dependencies have been added.
dapp/wagmi.config.ts:

The deployments section in the wagmi.config.ts configuration file has been modified to reflect contract deployment addresses.

### CODE REVIEW

**Comment by Keyrxng** [comment]
/ask extract the key metadata that you'd need to identify each of the various issues and prs, return your findings as a table

**Comment by Keyrxng** [comment]
/ask extract the key metadata that you'd need to identify each of the various issues and prs, return your findings as a table

**Comment by Keyrxng** [comment]
/ask create another table describing the context of each issue or pr you have found

**Comment by Keyrxng** [comment]
/ask return another table describing the context each of issue or pull request

**Comment by Keyrxng** [comment]
/ask identify which parts of your Original Context belongs to which issue or pr, analyse things before you answer

**Comment by Keyrxng** [comment]
/ask whats the first verse of Fast Car?

**Comment by Keyrxng** [comment]
/ask see time flies like an arrow, so fruit flies like a banana.

**Review by KxyChain — APPROVED** [review]
review

**Pull request closed without merging**
