### PR TITLE
Update README.md

### LINKED ISSUE #45: Improve README
**Issue Description**:
I would like to request an improvement to the README in this repository to make it more informative and user-friendly, taking inspiration from the README in the UbiquiBot repository.

**Specification for README Improvement**:

1. **Quickstart Section**:
   - Include a "Quickstart" section at the beginning of the README with code snippets for cloning the repository, installing dependencies, building, and starting the project.

2. **Environment Variables**:
   - Create a section titled "Environment Variables" to explain the necessary environment variables for configuring the project.
   - Include instructions for copying `.env.example` to `.env` and updating the fields with appropriate values.
   
3. **Overview Section**:
   - Add an "Overview" section that provides a high-level description of the project's purpose and how it functions.
   - Mention that the bot is designed to work as a GitHub Action.

4. **How to Use Section**:
   - Create a "How to Use" section explaining how to use the UbiquiBot.
   - Provide steps to install the bot from the [UbiquiBot App Marketplace](https://github.com/marketplace/ubiquibot).
   - Include instructions for testing the bot, such as creating a new issue, adding labels, and observing the bot's behavior.

5. **Configuration Section**:
   - Include a section that details the project's configuration options.
   - Explain the purpose of configuration settings like `evm-network-id`, `price-multiplier`, `time-labels`, `priority-labels`, and others.

6. **How to Run Locally Section**:
   - Add a section titled "How to Run Locally" with step-by-step instructions for running the project locally.
   - Include instructions for setting up the project with Supabase and Memzo.

7. **How It Works Section**:
   - Explain how the UbiquiBot functions, both as a GitHub app and a GitHub action.
   - Provide an overview of the flow of events when using the bot.

8. **Payments Permits in a Local Instance Section**:
   - If applicable, add a section explaining how to set up payment permits in a local instance.

9. **How to QA Any Additions to the Bot Section**:
   - If applicable, include a section on how to quality-assure any additions to the bot.
   - Provide steps for creating a QA issue and testing new features.

10. **How to Create a New Release Section**:
    - Include a section with instructions on how to create a new release of the project, including updating the version and creating tags.

11. **Architecture Overview Section**:
    - Provide an architecture overview of the project, including the structure of directories and key components.
    
12. **Default Config Notes Section**:
    - If applicable, include a section with notes on default configuration values.

13. **Supabase Cron Job Section**:
    - If applicable, explain how to set up a Supabase Cron Job.

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #45

I think I have achieved the spec here.

### CODE REVIEW

**Comment by Keyrxng** [comment]
readme is full of errors now, same prompt as last two when it was correct

**Comment by Keyrxng** [comment]
readme now matching spec perfectly

**Comment by Keyrxng** [comment]
about 10% spec achieved

**Comment by pavlovcik** [comment]
> ```diff
> ! You must configure the `openai-api-key` property in the bot configuration in order to use AI powered features.
> ```
> > <small> Ensure the pull request requirements are in the linked issue's first comment and update it if the scope evolves. </small>.

Use h6 or 
```
###### text
```

And no quote. Also you have a double punctuation

**Pull request closed without merging**
