### PR TITLE
Create NavBar.tsx

### LINKED ISSUE #53: New Navbar
Create a new navbar and it should be:

- top aligned
- always visible regardless of scroll height
- it should have an icon on the left
- it should have a theme toggle and settings on the right
- 3 buttons should span the middle, about, contact, demo

### PR DESCRIPTION
**Pull request by Keyrxng**
Resolves #53 

I have built the new navbar with the appropriate styling

### CODE REVIEW

**Comment by Keyrxng** [comment]
There spec has not been reached yet. 

There is an extra button and there is a missing closing tag for your  element

**Comment by Keyrxng** [comment]
Logs from above interactions

```
chatHistory [
  {
    role: 'system',
    content: '\n' +
      'Using the provided context, ensure you clearly understand the specification of the issue.\n' +
      'They must achieve the specification exactly as it is written, no less but more is acceptable.\n' +
      '\n' +
      'You are the first line of defense to ensure the specification is met before reviewers do their job.\n' +
      'If the specification is not met, you are to provide a clear and concise reason why.\n' +
      '\n' +
      'Your response will be posted as a GitHub comment for everyone to see in the pull request review conversation.\n' +
      'Knowing this, only include information that will benefit them, think of it as a summary of the review.\n' +
      'Do not add a list of changes made, you can add value by identifying errors and code suggestions that benefit both the author and reviewers..\n' +
      'Do not deviate from the provided examples below, use only their username, never use the @ symbol.\n' +
      'Always use the following format for your response, do not deviate from this format and do not add additional information.\n' +
      '\n' +
      '==If the spec is wrong==\n' +
      "### Haven't achieved specification\n" +
      '{username} this is where you went wrong...\n' +
      'this is how you can fix it... \n' +
      '> code example of solution\n' +
      '==If the spec is right==\n' +
      '### Have achieved specification\n' +
      '{username}, you have achieved the spec and now the reviewers will let you know if there are any other changes needed.\n' +
      '\n'
  },
  {
    role: 'assistant',
    content: 'Spec for Pr: \n' +
      `[{"role":"system","content":"This pull request context: \\n[{\\"login\\":\\"Keyrxng\\",\\"body\\":\\"Keyrxng's pull request description:\\\\nResolves #53 \\\\r\\\\n\\\\r\\\\nI have built the new navbar with the appropriate styling \\\\r\\\\n\\"},{\\"login\\":\\"assistant\\",\\"body\\":\\"#53 Specification: \\\\nCreate a new navbar and it should be:\\\\r\\\\n\\\\r\\\\n- top aligned\\\\r\\\\n- always visible regardless of scroll height\\\\r\\\\n- it should have an icon on the left\\\\r\\\\n- it should have a theme toggle and settings on the right\\\\r\\\\n- 3 buttons should span the middle, about, contact, demo\\"}]"}]`
  },
  {
    role: 'user',
    content: "Keyrxng's PR Diff: \n" +
      `"diff --git a/dapp/src/components/NavBar.tsx b/dapp/src/components/NavBar.tsx\\nnew file mode 100644\\nindex 0000000..a17e6b4\\n--- /dev/null\\n+++ b/dapp/src/components/NavBar.tsx\\n@@ -0,0 +1,46 @@\\n+import React from 'react';\\n+import { BaseError } from 'viem'; \\n+import { useAccount, useConnect, useDisconnect } from 'wagmi';\\n+\\n+function Navbar() {\\n+  const navbarStyle = { \\n+    display: 'flex',\\n+    alignItems: 'center',\\n+    justifyContent: 'space-between',\\n+    backgroundColor: '#333',\\n+    color: '#fff',\\n+    padding: '10px 20px',\\n+    marginLeft: '20px'\\n+  };\\n+\\n+  const buttonStyle = {\\n+    backgroundColor: '#555',\\n+    color: '#fff',\\n+    border: 'none',\\n+    borderRadius: '5px',\\n+    padding: '8px 12px',\\n+    marginRight: '10px',\\n+    cursor: 'pointer',\\n+    margin: '5px'\\n+  };\\n+\\n+  return (\\n+    <div style={navbarStyle}>\\n+      <div>\\n+        <img src=\\"icon.png\\" alt=\\"Icon\\" style={{ width: '40px', height: '40px' }}\\n+      </div>\\n+      <div>\\n+        <button style={buttonStyle}>About</button>\\n+        <button style={buttonStyle}>Contact</button>\\n+        <button style={buttonStyle}>Demo</button>\\n+        <button style={buttonStyle}>Error Button</button>\\n+      </div>\\n+      <div>\\n+        <button style={buttonStyle}>Theme</button>\\n+        <button style={buttonStyle}>Settings</button>\\n+      </div>\\n+    </div>\\n+  );\\n+}\\n+\\n+export default Navbar;\\n"`
  }
]
```

**Comment by pavlovcik** [comment]
> Keyrxng, you have made some progress on the pull request, but there are a few issues that need to be addressed:
> 
> 1. In the `navbarStyle` object, you have a syntax error. The `margin-left` property should be written as `marginLeft`.
> 2. In the `buttonStyle` object, you have two syntax errors. The `backgroundColor` property is duplicated and should be removed. Additionally, the `margin` property is missing a semicolon at the end.
> 
> Here's an example of how you can fix these issues:
> 
> ```js
> const navbarStyle = { 
>   display: 'flex',
>   alignItems: 'center',
>   justifyContent: 'space-between',
>   backgroundColor: '#333',
>   color: '#fff',
>   padding: '10px 20px',
>   marginLeft: '20px'
> };
> 
> const buttonStyle = {
>   backgroundColor: '#555',
>   color: '#fff',
>   border: 'none',
>   borderRadius: '5px',
>   padding: '8px 12px',
>   marginRight: '10px',
>   cursor: 'pointer',
>   margin: '5px'
> };
> ```
> 
> Please make these changes and resubmit your pull request.
> 
> > ###### Ensure the pull request requirements are in the linked issue's first comment and update it if the scope evolves.

This will be epic to eventually automatically add suggestions in the pull request review so we can instantly commit it to the code in the future...one day!

**Pull request closed without merging**
